// lib/features/presets/preset_registry.dart
//
// Luma Preset Registry
// - Matches the editor slider keys exactly (see EditorPage tool ids).
// - Includes a lightweight “photo type” ranking system.
// - Includes a preset icon system (stable, deterministic).
//
// Supported keys (must match EditorPage ids):
// exposure, contrast, highlights, shadows, whites, blacks
// tint, color_balance, vibrance, saturation
// texture, clarity, dehaze, grain, vignette
// sharpen, noise, color_noise
// lens_correction, chromatic_aberration
//
// Notes:
// - All values are normalized to the same ranges EditorPage expects.
//   * centered sliders: -1..1
//   * effect/detail sliders: 0..1
//   * toggles: 0 or 1

import 'preset_models.dart';

// -----------------------------------------------------------------------------
// Public API
// -----------------------------------------------------------------------------

class PresetRegistry {
  static const List<LumaPresetPack> packs = [
    LumaPresetPack(
      id: 'sunday_studio',
      name: 'Sunday Studio',
      description: 'Soft light, clean skin, quiet color.',
      presetIds: [
        'clean_natural',
        'portrait_skin_clean',
        'portrait_soft_matte',
        'bright_airy',
        'golden_hour_glow',
      ],
    ),
    LumaPresetPack(
      id: 'film',
      name: 'Film',
      description: 'Quiet analog, modern scans, fine texture.',
      presetIds: [
        'neutral_scan',
        'clean_roll',
        'warm_scan',
        'silver_soft',
        'film_warm',
      ],
    ),
    LumaPresetPack(
      id: 'roadside',
      name: 'Roadside',
      description: 'Warm drives, hard edges, city nights.',
      presetIds: [
        'film_warm',
        'street_contrast',
        'sunset_pop',
        'moody_cool',
        'cinematic_teal',
      ],
    ),
    LumaPresetPack(
      id: 'field_notes',
      name: 'Field Notes',
      description: 'Earth tones, depth, and texture.',
      presetIds: [
        'landscape_pop',
        'landscape_deep',
        'urban_grit',
        'vintage_fade',
        'film_cool',
      ],
    ),
    LumaPresetPack(
      id: 'nightroom',
      name: 'Nightroom',
      description: 'Low light, grain, and heavy contrast.',
      presetIds: [
        'soft_film',
        'moody_warm',
        'cinematic_dark',
        'black_white_classic',
        'black_white_grit',
      ],
    ),
  ];

  static const List<LumaPreset> all = [
    LumaPreset(
      id: 'clean_natural',
      name: 'Sunday',
      description: 'Soft balance, natural color, calm light.',
      bestFor: {
        LumaPhotoType.general,
        LumaPhotoType.portrait,
        LumaPhotoType.indoor,
      },
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.04,
        'contrast': 0.04,
        'highlights': -0.08,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.02,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.02,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.04,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'soft_film',
      name: 'Warm Static',
      description: 'Muted contrast, soft glow, subtle grain.',
      bestFor: {
        LumaPhotoType.softFilm,
        LumaPhotoType.portrait,
        LumaPhotoType.general,
      },
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.pastel),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.06,
        'contrast': -0.08,
        'highlights': -0.12,
        'shadows': 0.14,
        'whites': -0.04,
        'blacks': 0.06,
        'color_balance': 0.04,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': -0.04,
        'texture': -0.08,
        'clarity': -0.08,
        'dehaze': -0.04,
        'sharpen': 0.06,
        'noise': 0.10,
        'color_noise': 0.12,
        'grain': 0.22,
        'vignette': 0.12,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'neutral_scan',
      name: 'Neutral Scan',
      description: 'Straight scan, gentle contrast, clean grain.',
      bestFor: {
        LumaPhotoType.general,
        LumaPhotoType.portrait,
        LumaPhotoType.product,
      },
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.neutral),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.01,
        'contrast': 0.02,
        'highlights': -0.02,
        'shadows': 0.02,
        'whites': 0.00,
        'blacks': 0.03,
        'color_balance': 0.00,
        'tint': 0.00,
        'vibrance': 0.00,
        'saturation': 0.00,
        'texture': 0.00,
        'clarity': 0.00,
        'dehaze': 0.00,
        'sharpen': 0.06,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.10,
        'vignette': 0.02,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'clean_roll',
      name: 'Clean Roll',
      description: 'Neutral color, gentle contrast, fine grain.',
      bestFor: {
        LumaPhotoType.general,
        LumaPhotoType.portrait,
        LumaPhotoType.indoor,
      },
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.neutral),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.04,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.02,
        'blacks': -0.02,
        'color_balance': 0.00,
        'tint': 0.00,
        'vibrance': 0.02,
        'saturation': -0.02,
        'texture': 0.02,
        'clarity': 0.01,
        'dehaze': 0.00,
        'sharpen': 0.08,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.04,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'warm_scan',
      name: 'Warm Scan',
      description: 'Slight warmth, lifted mids, soft highlights.',
      bestFor: {
        LumaPhotoType.portrait,
        LumaPhotoType.indoor,
        LumaPhotoType.general,
      },
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.warm),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.04,
        'contrast': -0.02,
        'highlights': -0.10,
        'shadows': 0.10,
        'whites': -0.02,
        'blacks': 0.02,
        'color_balance': 0.06,
        'tint': 0.01,
        'vibrance': 0.04,
        'saturation': -0.02,
        'texture': -0.02,
        'clarity': -0.02,
        'dehaze': -0.02,
        'sharpen': 0.08,
        'noise': 0.08,
        'color_noise': 0.10,
        'grain': 0.18,
        'vignette': 0.06,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'silver_soft',
      name: 'Silver Soft',
      description: 'Cooler shadows, smooth tonal roll-off.',
      bestFor: {
        LumaPhotoType.general,
        LumaPhotoType.street,
        LumaPhotoType.indoor,
      },
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.cool),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.04,
        'highlights': -0.12,
        'shadows': 0.12,
        'whites': -0.04,
        'blacks': 0.04,
        'color_balance': -0.06,
        'tint': -0.01,
        'vibrance': -0.02,
        'saturation': -0.04,
        'texture': 0.00,
        'clarity': -0.02,
        'dehaze': -0.02,
        'sharpen': 0.08,
        'noise': 0.08,
        'color_noise': 0.10,
        'grain': 0.18,
        'vignette': 0.08,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'film_warm',
      name: 'Late Drive',
      description: 'Warmth up front, soft shadows, quiet blues.',
      bestFor: {
        LumaPhotoType.portrait,
        LumaPhotoType.indoor,
        LumaPhotoType.general,
      },
      icon: LumaPresetIcon(
        glyph: PresetGlyph.face,
        palette: PresetPalette(PresetPaletteId.warm),
      ),
      values: {
        'exposure': 0.04,
        'contrast': -0.02,
        'highlights': -0.12,
        'shadows': 0.10,
        'whites': -0.02,
        'blacks': 0.02,
        'color_balance': 0.08,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': -0.04,
        'texture': 0.02,
        'clarity': 0.02,
        'dehaze': 0.00,
        'sharpen': 0.08,
        'noise': 0.08,
        'color_noise': 0.10,
        'grain': 0.16,
        'vignette': 0.10,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'film_cool',
      name: 'Cold Air',
      description: 'Cool lift, quiet reds, soft blacks.',
      bestFor: {
        LumaPhotoType.street,
        LumaPhotoType.general,
        LumaPhotoType.indoor,
      },
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.cool),
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.04,
        'highlights': -0.10,
        'shadows': 0.12,
        'whites': -0.04,
        'blacks': 0.08,
        'color_balance': -0.08,
        'tint': -0.01,
        'vibrance': -0.02,
        'saturation': -0.06,
        'texture': 0.00,
        'clarity': 0.02,
        'dehaze': -0.02,
        'sharpen': 0.08,
        'noise': 0.08,
        'color_noise': 0.10,
        'grain': 0.16,
        'vignette': 0.12,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'vintage_fade',
      name: 'Dusty Light',
      description: 'Lifted blacks, faded color, gentle contrast.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.moody),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.04,
        'contrast': -0.14,
        'highlights': -0.08,
        'shadows': 0.18,
        'whites': -0.06,
        'blacks': 0.12,
        'color_balance': 0.02,
        'tint': 0.01,
        'vibrance': -0.08,
        'saturation': -0.12,
        'texture': -0.06,
        'clarity': -0.08,
        'dehaze': -0.02,
        'sharpen': 0.06,
        'noise': 0.10,
        'color_noise': 0.12,
        'grain': 0.24,
        'vignette': 0.18,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'bright_airy',
      name: 'Open Air',
      description: 'Light lift, soft contrast, clean whites.',
      bestFor: {LumaPhotoType.general, LumaPhotoType.vibrant},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.pastel),
      ),
      values: {
        'exposure': 0.14,
        'contrast': 0.02,
        'highlights': -0.08,
        'shadows': 0.12,
        'whites': 0.12,
        'blacks': -0.02,
        'vibrance': 0.08,
        'saturation': 0.02,
        'texture': 0.02,
        'clarity': -0.02,
        'dehaze': -0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.04,
        'vignette': 0.04,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'golden_hour_glow',
      name: 'Gold Hour',
      description: 'Warmth and glow, soft highlights.',
      bestFor: {LumaPhotoType.portrait, LumaPhotoType.vibrant},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.warm),
      ),
      values: {
        'exposure': 0.06,
        'contrast': 0.06,
        'highlights': -0.14,
        'shadows': 0.10,
        'whites': 0.06,
        'blacks': -0.04,
        'color_balance': 0.12,
        'tint': 0.04,
        'vibrance': 0.16,
        'saturation': 0.10,
        'texture': 0.06,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.08,
        'vignette': 0.08,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'sunset_pop',
      name: 'Crimson Sky',
      description: 'Richer reds, deeper contrast, vivid sky.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.vibrant},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.20,
        'highlights': -0.10,
        'shadows': 0.06,
        'whites': 0.08,
        'blacks': -0.12,
        'color_balance': 0.06,
        'tint': 0.06,
        'vibrance': 0.24,
        'saturation': 0.14,
        'texture': 0.12,
        'clarity': 0.12,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.08,
        'vignette': 0.12,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'moody_warm',
      name: 'Amber Room',
      description: 'Low light, warm shadows, gentle highs.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.warm),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.08,
        'contrast': 0.16,
        'highlights': -0.18,
        'shadows': 0.10,
        'whites': -0.02,
        'blacks': -0.14,
        'color_balance': 0.08,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.12,
        'sharpen': 0.10,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.16,
        'vignette': 0.18,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'moody_cool',
      name: 'Blue Hour',
      description: 'Cool shadows, muted warmth, quiet mood.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.cool),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.10,
        'contrast': 0.16,
        'highlights': -0.18,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': -0.16,
        'color_balance': -0.08,
        'tint': -0.02,
        'vibrance': 0.04,
        'saturation': -0.04,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.12,
        'sharpen': 0.10,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.16,
        'vignette': 0.18,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'cinematic_teal',
      name: 'Teal Fade',
      description: 'Teal lows, warm highs, cinematic contrast.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.landscape},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.moody),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.04,
        'contrast': 0.22,
        'highlights': -0.16,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.18,
        'color_balance': -0.10,
        'tint': 0.05,
        'vibrance': 0.10,
        'saturation': -0.02,
        'texture': 0.12,
        'clarity': 0.14,
        'dehaze': 0.16,
        'sharpen': 0.12,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.14,
        'vignette': 0.22,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'cinematic_dark',
      name: 'Night Plot',
      description: 'Crushed blacks, high contrast, muted color.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.moody),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.14,
        'contrast': 0.28,
        'highlights': -0.22,
        'shadows': 0.04,
        'whites': -0.04,
        'blacks': -0.28,
        'color_balance': -0.02,
        'tint': 0.01,
        'vibrance': -0.08,
        'saturation': -0.10,
        'texture': 0.16,
        'clarity': 0.18,
        'dehaze': 0.18,
        'sharpen': 0.14,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.18,
        'vignette': 0.26,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'urban_grit',
      name: 'Concrete',
      description: 'Hard detail, lower color, raw edge.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.00,
        'contrast': 0.18,
        'highlights': -0.12,
        'shadows': 0.06,
        'whites': 0.02,
        'blacks': -0.12,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': -0.10,
        'saturation': -0.18,
        'texture': 0.22,
        'clarity': 0.24,
        'dehaze': 0.16,
        'sharpen': 0.18,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.12,
        'vignette': 0.10,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'street_contrast',
      name: 'After Rain',
      description: 'Deep blacks, sharp edges, city punch.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.moody),
      ),
      values: {
        'exposure': -0.02,
        'contrast': 0.24,
        'highlights': -0.10,
        'shadows': 0.04,
        'whites': 0.06,
        'blacks': -0.20,
        'vibrance': 0.04,
        'saturation': -0.02,
        'texture': 0.16,
        'clarity': 0.18,
        'dehaze': 0.12,
        'sharpen': 0.20,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.12,
        'vignette': 0.14,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'portrait_skin_clean',
      name: 'Porcelain',
      description: 'Clean skin, reduced reds, soft highlights.',
      bestFor: {LumaPhotoType.portrait, LumaPhotoType.indoor},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.face,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.06,
        'contrast': 0.04,
        'highlights': -0.16,
        'shadows': 0.12,
        'whites': 0.04,
        'blacks': -0.04,
        'color_balance': 0.02,
        'tint': -0.02,
        'vibrance': 0.04,
        'saturation': -0.06,
        'texture': -0.08,
        'clarity': -0.06,
        'dehaze': -0.02,
        'sharpen': 0.08,
        'noise': 0.08,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.06,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'portrait_soft_matte',
      name: 'Studio Soft',
      description: 'Matte blacks, warm tone, soft contrast.',
      bestFor: {LumaPhotoType.portrait, LumaPhotoType.softFilm},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.face,
        palette: PresetPalette(PresetPaletteId.warm),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.04,
        'contrast': -0.08,
        'highlights': -0.10,
        'shadows': 0.16,
        'whites': -0.02,
        'blacks': 0.10,
        'color_balance': 0.06,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': -0.06,
        'clarity': -0.06,
        'dehaze': -0.02,
        'sharpen': 0.06,
        'noise': 0.10,
        'color_noise': 0.12,
        'grain': 0.18,
        'vignette': 0.12,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'landscape_pop',
      name: 'Greenfield',
      description: 'Boosted greens, clear detail, fresh light.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.vibrant},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mountain,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.04,
        'contrast': 0.16,
        'highlights': -0.12,
        'shadows': 0.06,
        'whites': 0.08,
        'blacks': -0.10,
        'color_balance': -0.04,
        'tint': 0.00,
        'vibrance': 0.22,
        'saturation': 0.10,
        'texture': 0.16,
        'clarity': 0.18,
        'dehaze': 0.18,
        'sharpen': 0.16,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.08,
        'vignette': 0.10,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'landscape_deep',
      name: 'Deep Ridge',
      description: 'Darker lift, rich color, bold contrast.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mountain,
        palette: PresetPalette(PresetPaletteId.moody),
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.22,
        'highlights': -0.16,
        'shadows': 0.06,
        'whites': 0.02,
        'blacks': -0.18,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.16,
        'saturation': 0.06,
        'texture': 0.16,
        'clarity': 0.18,
        'dehaze': 0.20,
        'sharpen': 0.18,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.10,
        'vignette': 0.14,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'black_white_classic',
      name: 'Linen Mono',
      description: 'Balanced contrast, clean highlight rolloff.',
      bestFor: {LumaPhotoType.blackAndWhite, LumaPhotoType.portrait},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.16,
        'highlights': -0.08,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.10,
        'vibrance': -0.30,
        'saturation': -0.60,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.08,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.10,
        'grain': 0.10,
        'vignette': 0.10,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),

    LumaPreset(
      id: 'black_white_grit',
      name: 'Grain Noir',
      description: 'Heavy contrast, grain and texture.',
      bestFor: {LumaPhotoType.blackAndWhite, LumaPhotoType.street},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.00,
        'contrast': 0.28,
        'highlights': -0.12,
        'shadows': 0.04,
        'whites': 0.02,
        'blacks': -0.22,
        'vibrance': -0.40,
        'saturation': -0.70,
        'texture': 0.18,
        'clarity': 0.22,
        'dehaze': 0.14,
        'sharpen': 0.16,
        'noise': 0.08,
        'color_noise': 0.10,
        'grain': 0.26,
        'vignette': 0.18,
        'lens_correction': 1.0,
        'chromatic_aberration': 1.0,
      },
    ),
    LumaPreset(
      id: 'film_amber',
      name: 'Amber Roll',
      description: 'Warm lift, soft grain, gentle contrast.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.pastel),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.04,
        'highlights': -0.12,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': 0.06,
        'color_balance': 0.14,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'film_matte',
      name: 'Matte Frame',
      description: 'Flattened contrast with quiet color.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.neutral),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.08,
        'highlights': -0.12,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': 0.10,
        'color_balance': 0.10,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.12,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'film_copper',
      name: 'Copper Grain',
      description: 'Copper warmth and lifted shadows.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.warm),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.04,
        'highlights': -0.12,
        'shadows': 0.10,
        'whites': -0.02,
        'blacks': 0.06,
        'color_balance': 0.16,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.12,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'film_dust',
      name: 'Dusty Negative',
      description: 'Muted color with airy blacks.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.moody),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.04,
        'highlights': -0.12,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': 0.12,
        'color_balance': 0.10,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.12,
        'vignette': 0.12,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'film_classic',
      name: 'Classic Roll',
      description: 'Balanced analog color and tone.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.02,
        'highlights': -0.12,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': 0.06,
        'color_balance': 0.10,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.12,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'film_mist',
      name: 'Soft Mist',
      description: 'Low contrast, light haze, soft grain.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.pastel),
        hasGrainHint: true,
        hasVignetteRing: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.10,
        'highlights': -0.12,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': 0.06,
        'color_balance': 0.10,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': -0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.16,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'film_night',
      name: 'Nightstock',
      description: 'Cool film for low light.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.cool),
        hasGrainHint: true,
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.04,
        'contrast': -0.04,
        'highlights': -0.12,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': 0.06,
        'color_balance': -0.06,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.18,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'film_soft',
      name: 'Soft Roll',
      description: 'Gentle highlights and warm midtone.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.pastel),
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.04,
        'highlights': -0.16,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': 0.06,
        'color_balance': 0.12,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.12,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'film_slate',
      name: 'Slate Film',
      description: 'Neutral shadows with subtle grain.',
      bestFor: {LumaPhotoType.softFilm, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.moody),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': -0.04,
        'highlights': -0.12,
        'shadows': 0.08,
        'whites': -0.02,
        'blacks': 0.06,
        'color_balance': -0.02,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.03,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.10,
        'color_noise': 0.08,
        'grain': 0.10,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_city',
      name: 'City Glow',
      description: 'Deep blacks and crisp highlights.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.moody),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.22,
        'highlights': -0.20,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.16,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.22,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_neon',
      name: 'Neon Street',
      description: 'Cool contrast with color pop.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.18,
        'highlights': -0.20,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.16,
        'color_balance': -0.08,
        'tint': 0.00,
        'vibrance': 0.10,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.20,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_mood',
      name: 'Midnight Mood',
      description: 'Soft shadows with strong contrast.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.moody),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.20,
        'highlights': -0.20,
        'shadows': 0.06,
        'whites': 0.02,
        'blacks': -0.16,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.20,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_slate',
      name: 'Slate Night',
      description: 'Cooler tone, tighter blacks.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.cool),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.18,
        'highlights': -0.20,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.20,
        'color_balance': -0.04,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.20,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_crisp',
      name: 'Crisp Night',
      description: 'Clarity and dehaze for detail.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.18,
        'highlights': -0.20,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.16,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.14,
        'dehaze': 0.16,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.20,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_glow',
      name: 'Soft Glow',
      description: 'Lifted shadows with gentle haze.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.pastel),
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.18,
        'highlights': -0.20,
        'shadows': 0.14,
        'whites': 0.02,
        'blacks': -0.16,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.06,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.20,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_silence',
      name: 'Silent Dark',
      description: 'Muted color, deep vignette.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.moody),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.18,
        'highlights': -0.20,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.16,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': -0.06,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.26,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_violet',
      name: 'Violet Night',
      description: 'Cool tint with soft contrast.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.cool),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.14,
        'highlights': -0.20,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.16,
        'color_balance': -0.02,
        'tint': 0.06,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.20,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_shadow',
      name: 'Shadowline',
      description: 'Dense blacks with tight highlights.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.moody),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.18,
        'highlights': -0.24,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.22,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.08,
        'vignette': 0.20,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'night_embers',
      name: 'Embers',
      description: 'Warm shadows and subtle grain.',
      bestFor: {LumaPhotoType.night, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.warm),
        hasGrainHint: true,
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.18,
        'highlights': -0.20,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.16,
        'color_balance': 0.10,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': -0.02,
        'texture': 0.08,
        'clarity': 0.10,
        'dehaze': 0.12,
        'sharpen': 0.12,
        'noise': 0.20,
        'color_noise': 0.18,
        'grain': 0.12,
        'vignette': 0.20,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'landscape_emerald',
      name: 'Emerald Ridge',
      description: 'Vivid greens and crisp detail.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mountain,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.04,
        'contrast': 0.12,
        'highlights': -0.08,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.10,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.18,
        'saturation': 0.06,
        'texture': 0.12,
        'clarity': 0.12,
        'dehaze': 0.12,
        'sharpen': 0.14,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.06,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'landscape_stone',
      name: 'Stone Trail',
      description: 'Neutral tone with punch.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mountain,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.04,
        'contrast': 0.14,
        'highlights': -0.08,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.10,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.14,
        'saturation': 0.06,
        'texture': 0.14,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.14,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.06,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'landscape_horizon',
      name: 'Horizon',
      description: 'Balanced contrast and clean skies.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mountain,
        palette: PresetPalette(PresetPaletteId.cool),
      ),
      values: {
        'exposure': 0.04,
        'contrast': 0.12,
        'highlights': -0.10,
        'shadows': 0.06,
        'whites': 0.06,
        'blacks': -0.10,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.14,
        'saturation': 0.06,
        'texture': 0.12,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.14,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.06,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'landscape_mist',
      name: 'Misty Pass',
      description: 'Soft contrast and lifted shadows.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mountain,
        palette: PresetPalette(PresetPaletteId.pastel),
      ),
      values: {
        'exposure': 0.04,
        'contrast': 0.06,
        'highlights': -0.08,
        'shadows': 0.10,
        'whites': 0.04,
        'blacks': -0.10,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.14,
        'saturation': 0.06,
        'texture': 0.12,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.14,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.06,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'landscape_glacier',
      name: 'Glacier',
      description: 'Cool clarity and depth.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mountain,
        palette: PresetPalette(PresetPaletteId.cool),
      ),
      values: {
        'exposure': 0.04,
        'contrast': 0.12,
        'highlights': -0.08,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.10,
        'color_balance': -0.06,
        'tint': 0.00,
        'vibrance': 0.14,
        'saturation': 0.06,
        'texture': 0.12,
        'clarity': 0.14,
        'dehaze': 0.10,
        'sharpen': 0.14,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.06,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'landscape_sienna',
      name: 'Sienna',
      description: 'Warm highlights and rich tone.',
      bestFor: {LumaPhotoType.landscape, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mountain,
        palette: PresetPalette(PresetPaletteId.warm),
      ),
      values: {
        'exposure': 0.04,
        'contrast': 0.12,
        'highlights': -0.08,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.10,
        'color_balance': 0.06,
        'tint': 0.00,
        'vibrance': 0.14,
        'saturation': 0.08,
        'texture': 0.12,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.14,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.06,
        'vignette': 0.10,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'street_concrete',
      name: 'Concrete',
      description: 'Hard edges with lifted grain.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.neutral),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.00,
        'contrast': 0.20,
        'highlights': -0.10,
        'shadows': 0.04,
        'whites': 0.02,
        'blacks': -0.18,
        'color_balance': 0.00,
        'tint': 0.00,
        'vibrance': 0.04,
        'saturation': 0.00,
        'texture': 0.14,
        'clarity': 0.18,
        'dehaze': 0.10,
        'sharpen': 0.16,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.18,
        'vignette': 0.16,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'street_flash',
      name: 'Flash',
      description: 'High contrast and bright whites.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.00,
        'contrast': 0.24,
        'highlights': -0.10,
        'shadows': 0.04,
        'whites': 0.06,
        'blacks': -0.18,
        'color_balance': 0.00,
        'tint': 0.00,
        'vibrance': 0.04,
        'saturation': 0.00,
        'texture': 0.14,
        'clarity': 0.16,
        'dehaze': 0.10,
        'sharpen': 0.16,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.16,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'street_rain',
      name: 'Rain',
      description: 'Cool shadows and softer highlights.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.cool),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': 0.00,
        'contrast': 0.20,
        'highlights': -0.14,
        'shadows': 0.04,
        'whites': 0.02,
        'blacks': -0.18,
        'color_balance': -0.06,
        'tint': 0.00,
        'vibrance': 0.04,
        'saturation': 0.00,
        'texture': 0.14,
        'clarity': 0.16,
        'dehaze': 0.10,
        'sharpen': 0.16,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.16,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'street_chrome',
      name: 'Chrome',
      description: 'Punchy detail with tight blacks.',
      bestFor: {LumaPhotoType.street, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.city,
        palette: PresetPalette(PresetPaletteId.moody),
      ),
      values: {
        'exposure': 0.00,
        'contrast': 0.20,
        'highlights': -0.10,
        'shadows': 0.04,
        'whites': 0.02,
        'blacks': -0.22,
        'color_balance': 0.00,
        'tint': 0.00,
        'vibrance': 0.04,
        'saturation': 0.00,
        'texture': 0.18,
        'clarity': 0.16,
        'dehaze': 0.10,
        'sharpen': 0.16,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.16,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_lamplight',
      name: 'Lamplight',
      description: 'Warm glow with gentle contrast.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.warm),
      ),
      values: {
        'exposure': 0.06,
        'contrast': -0.02,
        'highlights': -0.12,
        'shadows': 0.12,
        'whites': 0.02,
        'blacks': -0.04,
        'color_balance': 0.18,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_soft',
      name: 'Soft Interior',
      description: 'Low contrast and lifted shadows.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.leaf,
        palette: PresetPalette(PresetPaletteId.pastel),
      ),
      values: {
        'exposure': 0.06,
        'contrast': -0.06,
        'highlights': -0.10,
        'shadows': 0.14,
        'whites': 0.02,
        'blacks': -0.04,
        'color_balance': 0.12,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_canvas',
      name: 'Canvas',
      description: 'Neutral interior balance.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.leaf,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.06,
        'contrast': -0.02,
        'highlights': -0.10,
        'shadows': 0.12,
        'whites': 0.02,
        'blacks': -0.04,
        'color_balance': 0.08,
        'tint': 0.02,
        'vibrance': 0.04,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_cozy',
      name: 'Cozy',
      description: 'Warm midtones with subtle grain.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.warm),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.06,
        'contrast': -0.02,
        'highlights': -0.10,
        'shadows': 0.12,
        'whites': 0.02,
        'blacks': -0.04,
        'color_balance': 0.14,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.08,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_bright',
      name: 'Bright Room',
      description: 'Lifted exposure with smooth highlights.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.10,
        'contrast': -0.02,
        'highlights': -0.14,
        'shadows': 0.12,
        'whites': 0.02,
        'blacks': -0.04,
        'color_balance': 0.12,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_muse',
      name: 'Muse',
      description: 'Soft clarity and warm skin tone.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.leaf,
        palette: PresetPalette(PresetPaletteId.pastel),
      ),
      values: {
        'exposure': 0.06,
        'contrast': -0.02,
        'highlights': -0.10,
        'shadows': 0.12,
        'whites': 0.02,
        'blacks': -0.04,
        'color_balance': 0.12,
        'tint': 0.04,
        'vibrance': 0.06,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.06,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_cream',
      name: 'Cream',
      description: 'Muted contrast with creamy whites.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.pastel),
      ),
      values: {
        'exposure': 0.06,
        'contrast': -0.04,
        'highlights': -0.10,
        'shadows': 0.12,
        'whites': 0.06,
        'blacks': -0.04,
        'color_balance': 0.12,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_amber',
      name: 'Amber',
      description: 'Warm highlights and quiet shadows.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.warm),
      ),
      values: {
        'exposure': 0.06,
        'contrast': -0.02,
        'highlights': -0.10,
        'shadows': 0.10,
        'whites': 0.02,
        'blacks': -0.04,
        'color_balance': 0.16,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'indoor_evening',
      name: 'Evening',
      description: 'Dim warmth and deeper blacks.',
      bestFor: {LumaPhotoType.indoor, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.moody),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.02,
        'contrast': -0.02,
        'highlights': -0.10,
        'shadows': 0.12,
        'whites': 0.02,
        'blacks': -0.08,
        'color_balance': 0.12,
        'tint': 0.02,
        'vibrance': 0.06,
        'saturation': 0.04,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.12,
        'color_noise': 0.10,
        'grain': 0.04,
        'vignette': 0.08,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_soft',
      name: 'Soft Mono',
      description: 'Gentle contrast and clean tones.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.16,
        'highlights': -0.10,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.16,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.08,
        'vignette': 0.14,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_graphite',
      name: 'Graphite',
      description: 'Deep blacks and crisp edges.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.22,
        'highlights': -0.10,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.22,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.10,
        'clarity': 0.16,
        'dehaze': 0.10,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.14,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_crisp',
      name: 'Crisp Mono',
      description: 'Sharper contrast with clarity.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.26,
        'highlights': -0.10,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.16,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.16,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.14,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_highkey',
      name: 'High Key',
      description: 'Bright midtones, soft blacks.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
      ),
      values: {
        'exposure': 0.08,
        'contrast': 0.22,
        'highlights': -0.10,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.06,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.14,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_lowkey',
      name: 'Low Key',
      description: 'Dark tones and heavy vignette.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
        hasVignetteRing: true,
      ),
      values: {
        'exposure': -0.06,
        'contrast': 0.22,
        'highlights': -0.10,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.16,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.22,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_grain',
      name: 'Grain Mono',
      description: 'Heavy grain and texture.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.22,
        'highlights': -0.10,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.16,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.16,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.22,
        'vignette': 0.14,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_flat',
      name: 'Flat Mono',
      description: 'Low contrast, matte finish.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.08,
        'highlights': -0.10,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.08,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.14,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_silver',
      name: 'Silver',
      description: 'Classic silver tones.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.22,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.06,
        'blacks': -0.16,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.14,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'bw_matte',
      name: 'Matte Mono',
      description: 'Soft contrast with lifted blacks.',
      bestFor: {LumaPhotoType.blackAndWhite},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.mono,
        palette: PresetPalette(PresetPaletteId.mono),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.10,
        'highlights': -0.10,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.04,
        'vibrance': -0.60,
        'saturation': -0.90,
        'texture': 0.10,
        'clarity': 0.12,
        'dehaze': 0.10,
        'sharpen': 0.12,
        'noise': 0.08,
        'color_noise': 0.08,
        'grain': 0.14,
        'vignette': 0.14,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_pop',
      name: 'Pop',
      description: 'Color forward with clean contrast.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.10,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.06,
        'color_balance': 0.04,
        'tint': 0.00,
        'vibrance': 0.22,
        'saturation': 0.14,
        'texture': 0.06,
        'clarity': 0.06,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_tropic',
      name: 'Tropic',
      description: 'Warm saturation with soft contrast.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.leaf,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.10,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.06,
        'color_balance': 0.08,
        'tint': 0.00,
        'vibrance': 0.18,
        'saturation': 0.16,
        'texture': 0.06,
        'clarity': 0.06,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_citrus',
      name: 'Citrus',
      description: 'Bright highlights and punchy color.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.10,
        'highlights': -0.04,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.06,
        'color_balance': 0.04,
        'tint': 0.00,
        'vibrance': 0.20,
        'saturation': 0.12,
        'texture': 0.06,
        'clarity': 0.06,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_oasis',
      name: 'Oasis',
      description: 'Cool vibrance and clean shadows.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.drop,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.10,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.04,
        'blacks': -0.06,
        'color_balance': -0.02,
        'tint': 0.00,
        'vibrance': 0.18,
        'saturation': 0.12,
        'texture': 0.06,
        'clarity': 0.06,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_sunset',
      name: 'Sunset',
      description: 'Warmth with rich saturation.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.warm),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.10,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.06,
        'color_balance': 0.10,
        'tint': 0.00,
        'vibrance': 0.18,
        'saturation': 0.18,
        'texture': 0.06,
        'clarity': 0.06,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_lush',
      name: 'Lush',
      description: 'Deep color with clarity.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.leaf,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.10,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.06,
        'color_balance': 0.04,
        'tint': 0.00,
        'vibrance': 0.20,
        'saturation': 0.12,
        'texture': 0.06,
        'clarity': 0.10,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_magenta',
      name: 'Magenta',
      description: 'Slight magenta tint, vivid color.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.10,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.06,
        'color_balance': 0.04,
        'tint': 0.08,
        'vibrance': 0.18,
        'saturation': 0.14,
        'texture': 0.06,
        'clarity': 0.06,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_candy',
      name: 'Candy',
      description: 'High saturation, bright whites.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.10,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.06,
        'blacks': -0.06,
        'color_balance': 0.04,
        'tint': 0.00,
        'vibrance': 0.18,
        'saturation': 0.20,
        'texture': 0.06,
        'clarity': 0.06,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'vibrant_punch',
      name: 'Punch',
      description: 'Punchy contrast and saturation.',
      bestFor: {LumaPhotoType.vibrant, LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.vibrant),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.14,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.04,
        'blacks': -0.06,
        'color_balance': 0.04,
        'tint': 0.00,
        'vibrance': 0.18,
        'saturation': 0.16,
        'texture': 0.06,
        'clarity': 0.06,
        'dehaze': 0.04,
        'sharpen': 0.10,
        'noise': 0.04,
        'color_noise': 0.04,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_clean',
      name: 'Clean',
      description: 'Clean balance with subtle lift.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.03,
        'contrast': 0.06,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.06,
        'color_balance': 0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_soft',
      name: 'Soft',
      description: 'Gentle contrast and warm tone.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.pastel),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.04,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.06,
        'color_balance': 0.04,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_warm',
      name: 'Warm',
      description: 'Warm midtones and soft highlights.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.warm),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.06,
        'highlights': -0.08,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.06,
        'color_balance': 0.08,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_cool',
      name: 'Cool',
      description: 'Cooler balance with clean shadows.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.drop,
        palette: PresetPalette(PresetPaletteId.cool),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.06,
        'highlights': -0.06,
        'shadows': 0.06,
        'whites': 0.02,
        'blacks': -0.06,
        'color_balance': -0.04,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_matte',
      name: 'Matte',
      description: 'Light matte with gentle grain.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.film,
        palette: PresetPalette(PresetPaletteId.neutral),
        hasGrainHint: true,
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.02,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.06,
        'color_balance': 0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.06,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_air',
      name: 'Air',
      description: 'Lifted exposure and airy whites.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.06,
        'contrast': 0.06,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.06,
        'blacks': -0.06,
        'color_balance': 0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_dim',
      name: 'Dim',
      description: 'Softer exposure and deeper blacks.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.moon,
        palette: PresetPalette(PresetPaletteId.moody),
      ),
      values: {
        'exposure': -0.02,
        'contrast': 0.06,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.10,
        'color_balance': 0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_balance',
      name: 'Balance',
      description: 'Neutral balance and clean color.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.sun,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.06,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.06,
        'color_balance': 0.02,
        'tint': 0.00,
        'vibrance': 0.04,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_clear',
      name: 'Clear',
      description: 'Crisp detail with modest contrast.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.spark,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.06,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.06,
        'color_balance': 0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.08,
        'clarity': 0.08,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

    LumaPreset(
      id: 'everyday_simple',
      name: 'Simple',
      description: 'Minimal touch, natural look.',
      bestFor: {LumaPhotoType.general},
      icon: LumaPresetIcon(
        glyph: PresetGlyph.leaf,
        palette: PresetPalette(PresetPaletteId.neutral),
      ),
      values: {
        'exposure': 0.02,
        'contrast': 0.04,
        'highlights': -0.06,
        'shadows': 0.08,
        'whites': 0.02,
        'blacks': -0.06,
        'color_balance': 0.02,
        'tint': 0.00,
        'vibrance': 0.06,
        'saturation': 0.02,
        'texture': 0.04,
        'clarity': 0.04,
        'dehaze': 0.02,
        'sharpen': 0.08,
        'noise': 0.06,
        'color_noise': 0.06,
        'grain': 0.02,
        'vignette': 0.06,
        'lens_correction': 1.00,
        'chromatic_aberration': 1.00,
      },
    ),

  ];

  static LumaPreset byId(String id) => all.firstWhere((p) => p.id == id);

  static List<LumaPreset> presetsForPack(LumaPresetPack pack) {
    return pack.presetIds.map(byId).toList();
  }

  /// Returns presets ordered for a photo given simple metadata.
  /// You can feed:
  /// - aspect ratio (w/h)
  /// - isLowLight (from exposure time / ISO if you add EXIF later)
  /// - isPortraitGuess (if aspect is tall + face detection later)
  static List<LumaPreset> rankedFor({
    required double aspect, // width / height
    bool isLowLight = false,
    bool isIndoorGuess = false,
    bool isPortraitGuess = false,
  }) {
    final scores = <String, double>{};

    for (final p in all) {
      double s = 0;

      // base bias: general-friendly presets show higher
      if (p.bestFor.contains(LumaPhotoType.general)) s += 1.0;

      // portrait hints
      if (isPortraitGuess) {
        if (p.bestFor.contains(LumaPhotoType.portrait)) s += 3.0;
        if (p.id == 'portrait_skin_clean') s += 1.0;
      }

      // aspect hints
      final isWide = aspect > 1.25;
      final isTall = aspect < 0.85;
      if (isWide && p.bestFor.contains(LumaPhotoType.landscape)) s += 2.0;
      if (isTall && p.bestFor.contains(LumaPhotoType.portrait)) s += 1.5;

      // low light
      if (isLowLight && p.bestFor.contains(LumaPhotoType.night)) s += 3.0;

      // indoor guess
      if (isIndoorGuess && p.bestFor.contains(LumaPhotoType.indoor)) s += 2.0;

      // style clusters
      if (p.bestFor.contains(LumaPhotoType.vibrant)) s += 0.5;
      if (p.bestFor.contains(LumaPhotoType.softFilm)) s += 0.5;
      if (p.bestFor.contains(LumaPhotoType.blackAndWhite)) s += 0.2;

      // slight variety: stable pseudo-random based on id
      s += _stableJitter(p.id) * 0.08;

      scores[p.id] = s;
    }

    final list = [...all];
    list.sort((a, b) => (scores[b.id] ?? 0).compareTo(scores[a.id] ?? 0));
    return list;
  }
}

double _stableJitter(String s) {
  // deterministic 0..1 based on string
  int h = 2166136261;
  for (final c in s.codeUnits) {
    h ^= c;
    h = (h * 16777619) & 0x7fffffff;
  }
  return (h % 1000) / 1000.0;
}
